java:
  lang:
    Integer:
      IntegerCache:
        high:200

server:
  port: 8080


channelConfig:
  channel:
    - channelId: 40001
      token: df03f81e-9561-442c-8068-f40f304a81a5
      username: Connectadmin
      userId: 225
      currencyCode: 1000

id: 100

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/study?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
#  　　filters: stat,wall,log4j     #druid监控配置
#  　　dbcp2:
#    　　min-idle: 5         #数据库连接池的最小维持连接数
#    　　initial-size: 5     #初始化提供的连接数
#    　　max-total: 5          #最大的连接数
#    　　max-wait-millis: 200        #等待连接获取的最大超时时间

mybatis:
  mapper-locations: classpath:/mybatis/*.xml

